TYPE
ImConfig : STRUCT 
	Kran1 : struct_Kran;
	Kran4 : struct_Kran;
	Kran2 : struct_Kran;
	Kran3 : struct_Kran;
	Nu : struct_OilPump;
	Nu2 : struct_OilPump;
	Avom1 : struct_Switch;
	Avom2 : struct_Switch;
	Avom3 : struct_Switch;
	Avom4 : struct_Switch;
	Mv : struct_SectionSwitch;
	SectionSwitch1 : struct_SectionSwitch;
	SingleSignals : Im_singleSignals;
	SingleOutputs : Im_singleOutputs;
END_STRUCT;
END_TYPE